# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fototutucu = QtWidgets.QLabel(self.centralwidget)
        self.fototutucu.setGeometry(QtCore.QRect(450, 40, 381, 581))
        self.fototutucu.setObjectName("fototutucu")
        self.veritabanfoto = QtWidgets.QLabel(self.centralwidget)
        self.veritabanfoto.setGeometry(QtCore.QRect(20, 40, 351, 581))
        self.veritabanfoto.setObjectName("veritabanfoto")
        self.kisiadi = QtWidgets.QLabel(self.centralwidget)
        self.kisiadi.setGeometry(QtCore.QRect(910, 110, 149, 90))
        self.kisiadi.setObjectName("kisiadi")
        self.baslatmabutonu = QtWidgets.QPushButton(self.centralwidget)
        self.baslatmabutonu.setGeometry(QtCore.QRect(910, 40, 149, 61))
        self.baslatmabutonu.setObjectName("baslatmabutonu")
        self.kafatutucu = QtWidgets.QLabel(self.centralwidget)
        self.kafatutucu.setGeometry(QtCore.QRect(930, 250, 121, 81))
        self.kafatutucu.setObjectName("kafatutucu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fototutucu.setText(_translate("MainWindow", "TextLabel"))
        self.veritabanfoto.setText(_translate("MainWindow", "TextLabel"))
        self.kisiadi.setText(_translate("MainWindow", "Tespit edilen kisi:"))
        self.baslatmabutonu.setText(_translate("MainWindow", "Taramayı Başlat"))
        self.kafatutucu.setText(_translate("MainWindow", "TextLabel"))
