# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stacked.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 778)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 20, 961, 681))
        self.stackedWidget.setObjectName("stackedWidget")
        self.secim_ekrani = QtWidgets.QWidget()
        self.secim_ekrani.setObjectName("secim_ekrani")
        self.yoklama_alma = QtWidgets.QPushButton(self.secim_ekrani)
        self.yoklama_alma.setGeometry(QtCore.QRect(370, 410, 211, 131))
        self.yoklama_alma.setObjectName("yoklama_alma")
        self.ogrenci_ekleme = QtWidgets.QPushButton(self.secim_ekrani)
        self.ogrenci_ekleme.setGeometry(QtCore.QRect(370, 150, 211, 141))
        self.ogrenci_ekleme.setObjectName("ogrenci_ekleme")
        self.stackedWidget.addWidget(self.secim_ekrani)
        self.kayit_ekrani = QtWidgets.QWidget()
        self.kayit_ekrani.setObjectName("kayit_ekrani")
        self.fototutucu = QtWidgets.QLabel(self.kayit_ekrani)
        self.fototutucu.setGeometry(QtCore.QRect(240, 70, 480, 640))
        self.fototutucu.setMaximumSize(QtCore.QSize(1920, 1080))
        self.fototutucu.setText("")
        self.fototutucu.setObjectName("fototutucu")
        self.kafatutucu = QtWidgets.QLabel(self.kayit_ekrani)
        self.kafatutucu.setGeometry(QtCore.QRect(820, 100, 91, 71))
        self.kafatutucu.setText("")
        self.kafatutucu.setObjectName("kafatutucu")
        self.anamenuyedonus = QtWidgets.QPushButton(self.kayit_ekrani)
        self.anamenuyedonus.setGeometry(QtCore.QRect(780, 230, 171, 91))
        self.anamenuyedonus.setObjectName("anamenuyedonus")
        self.stackedWidget.addWidget(self.kayit_ekrani)
        self.yoklama = QtWidgets.QWidget()
        self.yoklama.setObjectName("yoklama")
        self.stackedWidget.addWidget(self.yoklama)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.yoklama_alma.setText(_translate("MainWindow", "Öğrenci Eklemek İçin Tıklayınız"))
        self.ogrenci_ekleme.setText(_translate("MainWindow", "Yoklama Almak İçin Tıklayınız"))
        self.anamenuyedonus.setText(_translate("MainWindow", "Ana ekrana dönmek için tıklayınız"))
